### ISSUE TITLE
Connector rotation incorrect

### ISSUE THREAD

**Issue by oliv3r** [30350n/pcb2blender#40]
I'm not sure if this is an issue with pcb2blender, or if the issue is elsewhere, so apologies if I'm reporting it in the wrong location.

My workflow is currently using kibot's docker kicad 7 full image, which should have all the tools installed. The configuration snippet I use,
```yaml
  - name: '3D_top_view'
    comment: '3D render from the top.'
    type: 'blender_export'
    dir: 'output/blender/'
    options:
      render_options:
        transparent_background: false
        samples: 1
      point_of_view:
        view: 'top'
      outputs:
        - type: 'blender'
        - type: 'render'
```

I made a PCB, which has a 3D file (from lcsc) but is abused ('its a through hole part, that I rendered rotated by 90 degrees to make it an edge connector). Also the lcsc part was offset, on the Z (-2.2) axis to compensate for the height, the X (-2.5) to get it from half the location to the correct location, and the Y (30.5) to move the pads in the correct spot. All in all, a few adjustment, but nothing major, and probably not relevant. (p.s. I realize that my story's coordinates don't match the offsets, but I'm sure you understand what I mean :p)

Opening the generated blender file, I see that the X and Z rotation are at -43.06 and 43.06. This is obviously wrong, which results in the following image.
![breakout_hdmi-3D_blender_top](https://github.com/30350n/pcb2blender/assets/1245341/bbdfc012-df5f-4583-ba95-49d4ba486efe)

Adjusting the X and Y rotations to -45 and +45, everything is perfect. So where do these rotations come from? Even though I'm abusing the wrong part, all modifications I made cause no problems in kicad itself. And the fact that both X and Z are incorrect by the same amount, and everything else is perfect, is surprising to me. I've attached the pcb3d (renamed to pcb3d.zip) but I'm not sure if all the needed information is in there. Who's responsible for mapping these transformations? Everything else renders really well.

[breakout_hdmi-blender_export.pcb3d.zip](https://github.com/30350n/pcb2blender/files/13694605/breakout_hdmi-blender_export.pcb3d.zip)
